version: '3'
services:
  database:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

  nextjs:
    container_name: nextjs
    build: .
    volumes:
      - .:/app
    depends_on:
      - database

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - 8080:8080


volumes:
  data: